### ISSUE TITLE
Details about the MKGC mission

### ISSUE THREAD

**Issue by dbbice** [vinhsuhi/JMAC#4]
First of all, thank you to the author for such valuable work. I have a question about the MKGC task, and I hope the author can help to answer it.  In the MKGC task, the five KGS were used to learn the features of nodes by GCN respectively for prediction, or were the five KGS aligned to see a complete graph and directly learn the features of nodes?

**Comment by vinhsuhi** [comment]
Thank you for your question. 

For each run, only one KG (e.g. ja) missing triples are predicted and the model is allowed to fully observe all the other KGs (es, el, fr, en). 

Five KGs were not aligned explicitly before performing the completion task but the model implicitly optimizes alignment loss among all pairs of KGs. The model is also trained to maximize scores of observed triples of all KGs.
