### ISSUE TITLE
RuntimeError: CUDA error:

### ISSUE THREAD

**Issue by dbbice** [vinhsuhi/JMAC#5]
Hello author, I found a memory overflow error when I used your code to run the MMKG dataset. The graphics card model is 3060. How can I solve this problem?
------------------------------------
(torch_1.12) E:\LP_code\JMAC-master>python train.py --data_path datasetmmkb15k/ --target_language fb --no_name_info --dropout 0.1
fb
11-Nov-22 09:37:57 - train - hello
11-Nov-22 09:37:57 - train - Using GPU--------------------------------------------------------------------------------
11-Nov-22 09:37:57 - train - Number of KGs is 3
11-Nov-22 09:37:57 - train - Number of KGs is 3
11-Nov-22 09:37:57 - train - Loading embedding name from file...
11-Nov-22 09:38:01 - train - Model initialization done!
  0%|                                                                                                                                            | 0/30 [00:00<?, ?it/s]1
1-Nov-22 09:38:01 - train - Epoch: 1
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:145: block: [121,0,0], thread: [110,0,0] Assertion `idx_dim >= 0 && idx_dim < index_siz
e && "index out of bounds"` failed.
  0%|                                                                                                                                            | 0/30 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 550, in <module>
    main(args, logger)
  File "train.py", line 450, in main
    output1, _ = model.get_emb(edge_index1, edge_type1, ent_bases1, rel_bases1, pyt=True)
  File "E:\LP_code\JMAC-master\src\jmac_model.py", line 227, in get_emb
    ent_align_output, ent_completion_outputs, _ = self.forward_base(edge_index, edge_type, ent_bases, rel_bases)
  File "E:\LP_code\JMAC-master\src\jmac_model.py", line 215, in forward_no_name
    ent_completion_output1 = self.conv1_completion(init_ent_completion_att, self.rel_init_att_completion[rel_bases[0]: rel_bases[1]], edge_index, edge_type)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\LP_code\JMAC-master\src\jmac_model.py", line 49, in forward
    message_neighbors = self.propagate('add', edge_index, x=ent_emb, edge_type=edge_type, rel_embed=rel_emb, edge_norm=norm, mode='in')
  File "E:\LP_code\JMAC-master\modules\helper\message_passing.py", line 86, in propagate
    out, score, edge_norm = self.message(*message_args)
  File "E:\LP_code\JMAC-master\src\jmac_model.py", line 87, in message
    score = self.compute_relation_aware_attention(x_i, rel_aware_message)
  File "E:\LP_code\JMAC-master\src\jmac_model.py", line 76, in compute_relation_aware_attention
    alpha = torch.mm(self.atv_mlp(torch.mm(combined, self.w_att)), self.a_att)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by vinhsuhi** [comment]
Hi, 

Thank you for your questions. 
This error indicates your machine does not have enough GPU memory. I would suggest using --device cpu or reduce the --dim from 256 to 128 or 100.
